version: "3.9"
services:
  frontend:
    image: ghcr.io/nicololuescher/flypast-frontend:latest
    links:
      - api
    ports:
      - "8080:80"
  api:
    image: ghcr.io/nicololuescher/flypast-backend:latest
    ports:
      - "8000:8000"
    environment:
      DB_HOST: database
      DB_USERNAME: flypast
      DB_PASSWORD: sohueresicherischdasgarnidemauso
      DB_NAME: flypast
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: flypast
      POSTGRES_PASSWORD: sohueresicherischdasgarnidemauso
      POSTGRES_DB: flypast
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flypast"]
      interval: 5s
      timeout: 5s
      retries: 5
  seed:
    image: ghcr.io/nicololuescher/flypast-seed:latest
    depends_on:
      - frontend
      - api
      - database
