version: "3.9"
services:
  frontend:
    build: src/frontend/flypast
    links:
      - api
    ports:
      - "8080:80"
  api:
    build: src/backend
    ports:
      - "8000:8000"
    environment:
      DB_HOST: database
    depends_on:
      database:
        condition: service_healthy
  database:
    image: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5